In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/load_data.csv')

print("1. Shape of raw data (rows, columns):", df.shape)
print("\n2. Columns with Missing Values (Blanks):")
missing = df.isnull().sum()
print(missing[missing > 0])

1. Shape of raw data (rows, columns): (35041, 9)

2. Columns with Missing Values (Blanks):
Usage_kWh                               1559
Lagging_Current_Reactive.Power_kVarh     876
Leading_Current_Reactive_Power_kVarh    1156
CO2(tCO2)                                455
Lagging_Current_Power_Factor             350
Leading_Current_Power_Factor            1471
NSM                                      455
dtype: int64

In [3]:
df

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,Load_Type
0,01-01-2018 00:15,8.753692,2.95,0.000000,0.0,73.210000,100.00,900.000000,Light_Load
1,01-01-2018 00:30,4.000000,4.46,0.000000,0.0,66.770000,100.00,1800.000000,Light_Load
2,01-01-2018 00:45,3.240000,3.28,0.000000,0.0,70.280000,100.00,8070.880991,Light_Load
3,01-01-2018 01:00,3.310000,3.56,0.000000,0.0,68.090000,100.00,3600.000000,Light_Load
4,01-01-2018 01:15,3.820000,4.50,0.000000,0.0,133.655666,NaN,4500.000000,Light_Load
...,...,...,...,...,...,...,...,...,...
35036,31-12-2018 23:15,3.740000,3.74,0.000000,0.0,70.710000,100.00,83700.000000,Light_Load
35037,31-12-2018 23:30,3.780000,3.17,0.070000,0.0,76.620000,99.98,157160.395291,Light_Load
35038,31-12-2018 23:45,3.780000,3.06,0.110000,0.0,187.054285,99.96,85500.000000,Light_Load
35039,31-12-2018 00:00,3.670000,3.02,0.174801,0.0,77.220000,NaN,0.000000,Light_Load
35040,31-12-2018 20:00,NaN,0.00,20.100000,0.0,217.273470,20.19,72000.000000,Light_Load

In [4]:
df.columns = df.columns.str.strip()

In [5]:
df['Load_Type'] = df['Load_Type'].astype(str).str.strip()
df

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,Load_Type
0,01-01-2018 00:15,8.753692,2.95,0.000000,0.0,73.210000,100.00,900.000000,Light_Load
1,01-01-2018 00:30,4.000000,4.46,0.000000,0.0,66.770000,100.00,1800.000000,Light_Load
2,01-01-2018 00:45,3.240000,3.28,0.000000,0.0,70.280000,100.00,8070.880991,Light_Load
3,01-01-2018 01:00,3.310000,3.56,0.000000,0.0,68.090000,100.00,3600.000000,Light_Load
4,01-01-2018 01:15,3.820000,4.50,0.000000,0.0,133.655666,NaN,4500.000000,Light_Load
...,...,...,...,...,...,...,...,...,...
35036,31-12-2018 23:15,3.740000,3.74,0.000000,0.0,70.710000,100.00,83700.000000,Light_Load
35037,31-12-2018 23:30,3.780000,3.17,0.070000,0.0,76.620000,99.98,157160.395291,Light_Load
35038,31-12-2018 23:45,3.780000,3.06,0.110000,0.0,187.054285,99.96,85500.000000,Light_Load
35039,31-12-2018 00:00,3.670000,3.02,0.174801,0.0,77.220000,NaN,0.000000,Light_Load
35040,31-12-2018 20:00,NaN,0.00,20.100000,0.0,217.273470,20.19,72000.000000,Light_Load

In [6]:
df = df.replace(r'^\s*$', np.nan, regex=True).replace('?', np.nan)
df

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,Load_Type
0,01-01-2018 00:15,8.753692,2.95,0.000000,0.0,73.210000,100.00,900.000000,Light_Load
1,01-01-2018 00:30,4.000000,4.46,0.000000,0.0,66.770000,100.00,1800.000000,Light_Load
2,01-01-2018 00:45,3.240000,3.28,0.000000,0.0,70.280000,100.00,8070.880991,Light_Load
3,01-01-2018 01:00,3.310000,3.56,0.000000,0.0,68.090000,100.00,3600.000000,Light_Load
4,01-01-2018 01:15,3.820000,4.50,0.000000,0.0,133.655666,NaN,4500.000000,Light_Load
...,...,...,...,...,...,...,...,...,...
35036,31-12-2018 23:15,3.740000,3.74,0.000000,0.0,70.710000,100.00,83700.000000,Light_Load
35037,31-12-2018 23:30,3.780000,3.17,0.070000,0.0,76.620000,99.98,157160.395291,Light_Load
35038,31-12-2018 23:45,3.780000,3.06,0.110000,0.0,187.054285,99.96,85500.000000,Light_Load
35039,31-12-2018 00:00,3.670000,3.02,0.174801,0.0,77.220000,NaN,0.000000,Light_Load
35040,31-12-2018 20:00,NaN,0.00,20.100000,0.0,217.273470,20.19,72000.000000,Light_Load

In [7]:
df = df.ffill().bfill()

In [8]:
print(df.isnull().sum())
df

Date_Time                               0
Usage_kWh                               0
Lagging_Current_Reactive.Power_kVarh    0
Leading_Current_Reactive_Power_kVarh    0
CO2(tCO2)                               0
Lagging_Current_Power_Factor            0
Leading_Current_Power_Factor            0
NSM                                     0
Load_Type                               0
dtype: int64

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,Load_Type
0,01-01-2018 00:15,8.753692,2.95,0.000000,0.0,73.210000,100.00,900.000000,Light_Load
1,01-01-2018 00:30,4.000000,4.46,0.000000,0.0,66.770000,100.00,1800.000000,Light_Load
2,01-01-2018 00:45,3.240000,3.28,0.000000,0.0,70.280000,100.00,8070.880991,Light_Load
3,01-01-2018 01:00,3.310000,3.56,0.000000,0.0,68.090000,100.00,3600.000000,Light_Load
4,01-01-2018 01:15,3.820000,4.50,0.000000,0.0,133.655666,100.00,4500.000000,Light_Load
...,...,...,...,...,...,...,...,...,...
35036,31-12-2018 23:15,3.740000,3.74,0.000000,0.0,70.710000,100.00,83700.000000,Light_Load
35037,31-12-2018 23:30,3.780000,3.17,0.070000,0.0,76.620000,99.98,157160.395291,Light_Load
35038,31-12-2018 23:45,3.780000,3.06,0.110000,0.0,187.054285,99.96,85500.000000,Light_Load
35039,31-12-2018 00:00,3.670000,3.02,0.174801,0.0,77.220000,99.96,0.000000,Light_Load
35040,31-12-2018 20:00,3.670000,0.00,20.100000,0.0,217.273470,20.19,72000.000000,Light_Load

In [9]:
# Convert Date_Time to datetime format
df['Date_Time'] = pd.to_datetime(df['Date_Time'], format='%d-%m-%Y %H:%M')

# 1. Hour of the day (0 to 23)
df['hour'] = df['Date_Time'].dt.hour

# 2. Day of the week (0 = Monday, 6 = Sunday)
df['dayofweek'] = df['Date_Time'].dt.dayofweek

# 3. Weekend flag (1 for Sat/Sun, 0 for Mon-Fri)
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)

# 4. Month (1 to 12) - needed for splitting the last month!
df['month'] = df['Date_Time'].dt.month
df

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,Load_Type,hour,dayofweek,is_weekend,month
0,2018-01-01 00:15:00,8.753692,2.95,0.000000,0.0,73.210000,100.00,900.000000,Light_Load,0,0,0,1
1,2018-01-01 00:30:00,4.000000,4.46,0.000000,0.0,66.770000,100.00,1800.000000,Light_Load,0,0,0,1
2,2018-01-01 00:45:00,3.240000,3.28,0.000000,0.0,70.280000,100.00,8070.880991,Light_Load,0,0,0,1
3,2018-01-01 01:00:00,3.310000,3.56,0.000000,0.0,68.090000,100.00,3600.000000,Light_Load,1,0,0,1
4,2018-01-01 01:15:00,3.820000,4.50,0.000000,0.0,133.655666,100.00,4500.000000,Light_Load,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35036,2018-12-31 23:15:00,3.740000,3.74,0.000000,0.0,70.710000,100.00,83700.000000,Light_Load,23,0,0,12
35037,2018-12-31 23:30:00,3.780000,3.17,0.070000,0.0,76.620000,99.98,157160.395291,Light_Load,23,0,0,12
35038,2018-12-31 23:45:00,3.780000,3.06,0.110000,0.0,187.054285,99.96,85500.000000,Light_Load,23,0,0,12
35039,2018-12-31 00:00:00,3.670000,3.02,0.174801,0.0,77.220000,99.96,0.000000,Light_Load,0,0,0,12
35040,2018-12-31 20:00:00,3.670000,0.00,20.100000,0.0,217.273470,20.19,72000.000000,Light_Load,20,0,0,12

In [10]:
# Training set: January to November (Months 1 to 11)
train_df = df[df['month'] < 12].copy()

# Test set: December (Month 12 - Last Month as required by assignment)
test_df = df[df['month'] == 12].copy()

print(f"Training samples (Jan - Nov): {len(train_df)}")
print(f"Testing samples (December): {len(test_df)}")

Training samples (Jan - Nov): 32064
Testing samples (December): 2977

In [11]:
df

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,Load_Type,hour,dayofweek,is_weekend,month
0,2018-01-01 00:15:00,8.753692,2.95,0.000000,0.0,73.210000,100.00,900.000000,Light_Load,0,0,0,1
1,2018-01-01 00:30:00,4.000000,4.46,0.000000,0.0,66.770000,100.00,1800.000000,Light_Load,0,0,0,1
2,2018-01-01 00:45:00,3.240000,3.28,0.000000,0.0,70.280000,100.00,8070.880991,Light_Load,0,0,0,1
3,2018-01-01 01:00:00,3.310000,3.56,0.000000,0.0,68.090000,100.00,3600.000000,Light_Load,1,0,0,1
4,2018-01-01 01:15:00,3.820000,4.50,0.000000,0.0,133.655666,100.00,4500.000000,Light_Load,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35036,2018-12-31 23:15:00,3.740000,3.74,0.000000,0.0,70.710000,100.00,83700.000000,Light_Load,23,0,0,12
35037,2018-12-31 23:30:00,3.780000,3.17,0.070000,0.0,76.620000,99.98,157160.395291,Light_Load,23,0,0,12
35038,2018-12-31 23:45:00,3.780000,3.06,0.110000,0.0,187.054285,99.96,85500.000000,Light_Load,23,0,0,12
35039,2018-12-31 00:00:00,3.670000,3.02,0.174801,0.0,77.220000,99.96,0.000000,Light_Load,0,0,0,12
35040,2018-12-31 20:00:00,3.670000,0.00,20.100000,0.0,217.273470,20.19,72000.000000,Light_Load,20,0,0,12

In [12]:
# List of input columns we want the model to learn from
features = [
    'Usage_kWh', 
    'Lagging_Current_Reactive.Power_kVarh',
    'Leading_Current_Reactive_Power_kVarh', 
    'CO2(tCO2)',
    'Lagging_Current_Power_Factor', 
    'Leading_Current_Power_Factor', 
    'hour', 
    'dayofweek', 
    'is_weekend'
]

# Separate features (X) and label (y)
X_train = train_df[features]
y_train = train_df['Load_Type']

X_test = test_df[features]
y_test = test_df['Load_Type']

print("Features X_train shape:", X_train.shape)
print("Target y_train shape:", y_train.shape)

Features X_train shape: (32064, 9)
Target y_train shape: (32064,)

In [17]:
df

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,Load_Type,hour,dayofweek,is_weekend,month
0,2018-01-01 00:15:00,8.753692,2.95,0.000000,0.0,73.210000,100.00,900.000000,Light_Load,0,0,0,1
1,2018-01-01 00:30:00,4.000000,4.46,0.000000,0.0,66.770000,100.00,1800.000000,Light_Load,0,0,0,1
2,2018-01-01 00:45:00,3.240000,3.28,0.000000,0.0,70.280000,100.00,8070.880991,Light_Load,0,0,0,1
3,2018-01-01 01:00:00,3.310000,3.56,0.000000,0.0,68.090000,100.00,3600.000000,Light_Load,1,0,0,1
4,2018-01-01 01:15:00,3.820000,4.50,0.000000,0.0,133.655666,100.00,4500.000000,Light_Load,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35036,2018-12-31 23:15:00,3.740000,3.74,0.000000,0.0,70.710000,100.00,83700.000000,Light_Load,23,0,0,12
35037,2018-12-31 23:30:00,3.780000,3.17,0.070000,0.0,76.620000,99.98,157160.395291,Light_Load,23,0,0,12
35038,2018-12-31 23:45:00,3.780000,3.06,0.110000,0.0,187.054285,99.96,85500.000000,Light_Load,23,0,0,12
35039,2018-12-31 00:00:00,3.670000,3.02,0.174801,0.0,77.220000,99.96,0.000000,Light_Load,0,0,0,12
35040,2018-12-31 20:00:00,3.670000,0.00,20.100000,0.0,217.273470,20.19,72000.000000,Light_Load,20,0,0,12

In [18]:

df['Lagging_Current_Power_Factor'] = df['Lagging_Current_Power_Factor'].clip(0, 100)
df['Leading_Current_Power_Factor'] = df['Leading_Current_Power_Factor'].clip(0, 100)
df['NSM'] = df['NSM'].clip(0, 86400)


df['Usage_kWh_lag1'] = df['Usage_kWh'].shift(1).bfill()
df['Usage_kWh_rolling_mean_4'] = df['Usage_kWh'].rolling(window=4, min_periods=1).mean()

# Total Apparent Power
reactive_total = df['Lagging_Current_Reactive.Power_kVarh'] + df['Leading_Current_Reactive_Power_kVarh']
df['Apparent_Power'] = np.sqrt(df['Usage_kWh']**2 + reactive_total**2)


train_df = df[df['month'] < 12].copy()
test_df  = df[df['month'] == 12].copy()


features = [
    'Usage_kWh', 
    'Lagging_Current_Reactive.Power_kVarh',
    'Leading_Current_Reactive_Power_kVarh', 
    'CO2(tCO2)',
    'Lagging_Current_Power_Factor', 
    'Leading_Current_Power_Factor', 
    'NSM',
    'hour', 
    'dayofweek', 
    'is_weekend',
    'Usage_kWh_lag1',
    'Usage_kWh_rolling_mean_4',
    'Apparent_Power'
]

X_train = train_df[features]
y_train = train_df['Load_Type']

X_test = test_df[features]
y_test = test_df['Load_Type']


model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print(f"New Overall Accuracy on December Test Set: {acc * 100:.2f}%\n")
print("--- New Classification Report ---")
print(classification_report(y_test, y_pred))

New Overall Accuracy on December Test Set: 75.11%

--- New Classification Report ---
              precision    recall  f1-score   support

  Light_Load       0.98      0.92      0.95      1745
Maximum_Load       0.44      0.49      0.46       528
 Medium_Load       0.49      0.52      0.50       704

    accuracy                           0.75      2977
   macro avg       0.64      0.64      0.64      2977
weighted avg       0.77      0.75      0.76      2977

In [14]:
from sklearn.ensemble import RandomForestClassifier

# 1. Initialize the Random Forest model with 100 decision trees
model = RandomForestClassifier(n_estimators=100, random_state=42)

# 2. Train (Fit) the model using the training data
model.fit(X_train, y_train)

print("Model training completed successfully!")

Model training completed successfully!

In [15]:
# Lets generate predictions for the unseen December test set
y_pred = model.predict(X_test)

# Quick peek at the first 10 predictions vs actual answers
comparison_df = pd.DataFrame({
    'Actual_Load': y_test.values[:20],
    'Predicted_Load': y_pred[:20],
    #for easy finding mistakes
    'Match': y_test.values[:20] == y_pred[:20]
})
print(comparison_df)

   Actual_Load Predicted_Load  Match
0   Light_Load     Light_Load   True
1   Light_Load     Light_Load   True
2   Light_Load     Light_Load   True
3   Light_Load     Light_Load   True
4   Light_Load     Light_Load   True
5   Light_Load     Light_Load   True
6   Light_Load     Light_Load   True
7   Light_Load     Light_Load   True
8   Light_Load     Light_Load   True
9   Light_Load     Light_Load   True
10  Light_Load     Light_Load   True
11  Light_Load     Light_Load   True
12  Light_Load     Light_Load   True
13  Light_Load     Light_Load   True
14  Light_Load     Light_Load   True
15  Light_Load     Light_Load   True
16  Light_Load     Light_Load   True
17  Light_Load     Light_Load   True
18  Light_Load     Light_Load   True
19  Light_Load     Light_Load   True

In [16]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# 1. Overall Accuracy
acc = accuracy_score(y_test, y_pred)
print(f"Overall Accuracy on December Test Set: {acc * 100:.2f}%\n")

# 2. Full Classification Report (Precision, Recall, F1-Score per class)
print("--- Classification Report ---")
print(classification_report(y_test, y_pred))

Overall Accuracy on December Test Set: 72.76%

--- Classification Report ---
              precision    recall  f1-score   support

  Light_Load       0.96      0.90      0.93      1745
Maximum_Load       0.42      0.49      0.45       528
 Medium_Load       0.46      0.48      0.47       704

    accuracy                           0.73      2977
   macro avg       0.61      0.62      0.62      2977
weighted avg       0.75      0.73      0.74      2977

In [21]:
# ================================================================
# Model Experiment 2: Adding 'Usage_diff' + Balanced Class Weights
# ================================================================

# 1. Create power acceleration feature (Is consumption rising or falling?)
df['Usage_diff'] = (df['Usage_kWh'] - df['Usage_kWh_lag1']).astype('float64')

# 2. Re-slice Train and Test with the new column included
train_df = df[df['month'] < 12].copy()
test_df  = df[df['month'] == 12].copy()

# 3. Complete feature list
features_v2 = [
    'Usage_kWh', 
    'Lagging_Current_Reactive.Power_kVarh',
    'Leading_Current_Reactive_Power_kVarh', 
    'CO2(tCO2)',
    'Lagging_Current_Power_Factor', 
    'Leading_Current_Power_Factor', 
    'NSM',
    'hour', 
    'dayofweek', 
    'is_weekend',
    'Usage_kWh_lag1',
    'Usage_kWh_rolling_mean_4',
    'Apparent_Power',
    'Usage_diff'
]

X_train = train_df[features_v2]
y_train = train_df['Load_Type']
X_test  = test_df[features_v2]
y_test  = test_df['Load_Type']

# 4. Train with balanced class weights to pay extra attention to Maximum and Medium loads
model_balanced = RandomForestClassifier(
    n_estimators=150, 
    class_weight='balanced', 
    random_state=42, 
    n_jobs=-1
)
model_balanced.fit(X_train, y_train)

# 5. Predict and print classification report
y_pred_balanced = model_balanced.predict(X_test)

print(f"Accuracy with Balanced Random Forest: {accuracy_score(y_test, y_pred_balanced) * 100:.2f}%\n")
print("--- Classification Report (Balanced Model) ---")
print(classification_report(y_test, y_pred_balanced))

Accuracy with Balanced Random Forest: 74.47%

--- Classification Report (Balanced Model) ---
              precision    recall  f1-score   support

  Light_Load       0.99      0.91      0.95      1745
Maximum_Load       0.45      0.51      0.48       528
 Medium_Load       0.47      0.51      0.49       704

    accuracy                           0.74      2977
   macro avg       0.64      0.64      0.64      2977
weighted avg       0.77      0.74      0.76      2977